src/components/Chat/styled.ts
**Fixes or implements CT-1043**
This took me so fucking long to figure out I think its good to dedicate an entire PR for it.
I had to record the screen and play it frame by frame to see what was going on.
<video src="https://user-images.githubusercontent.com/5643574/193352800-72572ac5-1326-4fdd-b5d3-a6da8116e30e.mov"/>
As it is animating in from the bottom, the `translateY` diff is getting calculated in as part of the overall height of the element.
It turns out this is because we just start the element off with `transform: 'translateY(${distance}px)',` and the rendering is all fucked up. If we remove it and let the animation handle the initial state of the transform, it's totally fine:
https://github.com/voiceflow/react-chat/blob/0c1ec07c520b969283c428e2f39c7899d1cf60ee/src/styles/animatio …
=> fix: new message height shift (CT-1043)

src/components/Card/styled.ts, src/components/Carousel/styled.ts, src/components/Chat/index.tsx, src/components/Chat/styled.ts, src/components/SystemResponse/SystemMessage.tsx, src/components/SystemResponse/index.tsx, src/components/SystemResponse/styled.ts, src/components/Timestamp/styled.ts
**Fixes or implements CT-1040, CT-1039, CT-1041**
Because we added a new `span` to `SystemMessage`, this was always going to fail:
https://github.com/voiceflow/react-chat/blob/562c937bcdfd40ca1be84b1f1a54904a79cefb14/src/components/Chat/styled.ts#L140-L143
There is now a `span` in between them. I just accounted for it.
The carousel buttons are in the wrong place because they are position absolute and not relative to anything.
I REALLY wish there was some better way to do the controls, because I believe this just pollutes the dom with these spans that we never use. But I've tried for over 2 hours with some kind of potential hack CSS solution and nothing has worked. I give up.
=> fix: carousel span buttons (CT-1040) (CT-1039)

README.md, package.json, src/hooks/useRuntime.ts, src/views/ChatWidget/ChatWidget.story.tsx, src/views/ChatWidget/index.tsx, yarn.lock
**Fixes or implements CT-1046**
This PR depended on this part of `sdk-runtime` being merged: https://github.com/voiceflow/adapters/pull/41
While the SDK can accept either an API key or projectID under the `verify` option - we only ever want to expose the `projectID` option - which is why I overrode the type. No one on the frontend should ever be using the API key version with access to underlying logging and debugging methods.
=> fix: public endpoint (CT-1046)

src/components/Carousel/CarouselButton.tsx, src/components/Carousel/index.tsx, src/components/Carousel/styled.ts
the carousel button practically overrides every attribute of Bubble
There's been multiple instances where we applied some style to Bubble.Container and it had some adverse effect either on the carousel button or other buttons.
I think it's better to leave them distinct for now. We also don't need the wrapper anymore which is nice.
=> fix: move carousel button to separate component

packages/widget/index.tsx
We need a way to know when the actual `ChatWidget` is ready so that we can call `window.voiceflow.chat.open`
Otherwise, that `open` call will never work.
After this implementation the intended goal is:
```
window.voiceflow.chat.load({
url: 'https://general-runtime.development.voiceflow.com',
verify: { projectID: 'xxx-123-xxx-456' },
user: {
name: 'Development User',
},
}).then(() => window.voiceflow.chat.open());
```
=> fix: resolve promise on load session (CT-000)

.circleci/continue-config.yml
- seems like we're using an old container with an incompatible node engine
https://app.circleci.com/pipelines/github/voiceflow/react-chat/857/workflows/f07993d8-c816-4ea6-aa6b-532bc02b992c/jobs/1340/parallel-runs/0/steps/0-110
=> fix: release monorepo task

packages/react-chat/src/components/Feedback/index.tsx, packages/react-chat/src/components/SystemResponse/index.tsx, packages/react-chat/src/hooks/useRuntime.ts, packages/react-chat/src/views/ChatWindow/index.tsx
**Fixes or implements CT-2094**
- Send all ai messages in the turn instead of only the first one
- Send last user turn before the one user is giving feedback 
Did some cleanup to reduce the spread of feedback logic
=> feat: include last user turn in the feedback (CT-2094)

packages/react-chat/src/common/types.ts, packages/react-chat/src/components/SystemResponse/SystemMessage.tsx, packages/react-chat/src/components/SystemResponse/types.ts, packages/react-chat/src/hooks/useRuntime.ts, packages/react-chat/src/runtime.ts, packages/react-chat/src/views/ChatWindow/index.tsx
- expose `traces` option to configure runtime declaratively
- avoid using `verify` as a dependency for memoization since it may be created during render
- make it easier to reuse `SystemMessage` without the matching logic
- make `message` prop optional
=> fix: use traces to avoid re-render issues (DX-000)

packages/react-chat/src/hocs/tag.tsx
https://voiceflow.atlassian.net/jira/software/c/projects/BUG/boards/24?modal=detail&selectedIssue=BUG-484
allow refs to be passed to the tagFactory function
=> fix: update tagFactory to allow refs (CT-000)

packages/react-chat/src/styles/theme.ts, packages/react-chat/src/views/ChatWidget/index.tsx, packages/react-chat/src/views/ChatWidget/styled.ts
- make `ChatContainer` and `ChatWidget` mobile-aware
=> feat: basic mobile support (DX-000)

packages/react-chat/src/hooks/useRuntime.ts
**Fixes or implements DX-610**
Fix an infinite looping issue that occurs when the chat ends
=> fix: do not set the status if it is already set (DX-610)

package.json, packages/react-chat/src/components/Text/Markdown.tsx, yarn.lock
I went down a bit of a deep rabbit hole for this one.
So first off, in Markdown, it is standard practice to collapse spaces:
If I wrote "test&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;test"
it would show up as "test     test", the only reason the ^above works is because I injected in `&nbsp;` characters.
For the most part, our text editor works to the same extent as the Github Markdown.
HOWEVER, for regular people who don't use markdown, they expect their spaces to be shown properly. If I type 5 spaces on Microsoft word, I should have 5 spaces. This is why in the styling we have:
https://github.com/voiceflow/react-chat/blob/1e76651fdfa9a015b0a689e4fefd6c4e0a8b5cee/packages/react-chat/src/components/Text/Markdown.tsx#L17-L20
The `prewrap` helps preserve all the whitespace and is essential to …
=> fix: remove break br tag insertion (CV3-370)

packages/react-chat/package.json, packages/react-chat/src/browser/utils.ts, packages/react-chat/src/common/types.ts, packages/react-chat/src/utils/stylesheet.ts, packages/react-chat/src/views/ChatWidget/index.tsx, packages/react-chat/src/views/ChatWindow/index.tsx, packages/widget/src/config.ts, packages/widget/src/index.tsx, yarn.lock
Users can now initialize stylesheets like this:
```
window.voiceflow.chat.load({
...
assistant: {
stylesheet: 'http://test.com/test.css',
},
});
```
This leaves the path open to expose this on the GUI in the future since it is part of the `Assistant` object type.
This is necessary just because of how iframes don't handle root page styles. This stylesheet gets injected both into the main page AND the iframe
=> fix: allow custom css stylesheets (CT-000)

packages/react-chat/index.ts, packages/react-chat/package.json, packages/react-chat/src/browser/index.tsx, packages/react-chat/src/common/listeners.ts, packages/react-chat/src/common/postMessage.ts, packages/react-chat/src/constants.ts, packages/react-chat/src/hooks/useRuntime.ts, packages/react-chat/src/styles/index.ts, packages/react-chat/src/views/ChatWidget/index.tsx, packages/react-chat/src/views/ChatWindow/index.tsx, packages/react-chat/src/views/ChatWindow/utils.ts, packages/widget/package.json, packages/widget/src/api/assistant.ts, packages/widget/src/api/constants.ts, packages/widget/src/api/listeners.ts, packages/widget/src/index.tsx, yarn.lock
This is not at all the prettiest code, but the goal here was to move ALL `general-runtime` api calls outside of the iframe itself and into the bundle.mjs that the script injects. I can clean things up more later.
This allows the browser to say the "origin" of the call is from the embedded website.
I'm heavily relying on our "listener" system to send messages where there used to be an API call.
I've tested that transcripts continue to work
react-chat still works
I'm not sure how to test the feedback system.
=> fix: move api out of react-chat (CT-000)

packages/react-chat/src/common/types.ts, packages/react-chat/src/hooks/useRuntime.ts, packages/react-chat/src/views/ChatWindow/index.tsx
users can now add something like:
```
launch: {
event: { type: 'launch', payload: { internalUserID: 1345, email: "test@voiceflow.com" } }
}
```
to pass additional context when the chat starts. They can also start it with a particular event or from a particular intent. This provides more optionality of starting from different diagrams.
=> fix: launch options (CT-000)

.circleci/continue-config.yml
Use latest sonarcloud orb vesrsion
=> ci(sonar): use latest sonarcloud orb (IN-976)

packages/react-chat/src/components/SystemResponse/constants.ts, packages/react-chat/src/components/SystemResponse/hooks.ts, packages/react-chat/src/contexts/RuntimeContext/index.tsx, packages/react-chat/src/contexts/RuntimeContext/useNoReply.ts, packages/react-chat/src/contexts/RuntimeContext/useRuntimeState.ts
The old `useEffect(, [noReplyTimeout, lastInteractionAt])` system was totally broken, and also very hard to follow and read. Fraught with side effects.
I have no idea why they had to be calculated independently.
there was no way to reset `noReplyTimeout` so it was ALWAYS on. `lastInteractionAt` would always change so it would always reset the `noReplyTimeout`.
This would mean the moment you set a NoReply, for the rest of the conversation NoReply would apply.
I've abstracted it into a new explicit API: `clearNoReplyTimeout` and `setNoReplyTimeout`
I've also adjusted how we were calculating the timeout.
=> fix: no reply timeout (ACT-014)

packages/react-chat/src/components/ChatInput/index.tsx
Before we had an iframe and all events would've been separated.
I've tested with the reported customer's website using the `/alpha/` bundle and this fixes their issue. As long as there are no other serious side effects, this is fine.
=> fix: stop event propagation from chat input (ACT-000)

packages/react-chat/src/contexts/RuntimeContext/useRuntimeState.ts, packages/react-chat/src/utils/broadcast.ts
**Fixes or implements DX-1078**
Add a unique event `voiceflow:interact` that can be used to capture all user interactions (and allows us to evolve `voiceflow:save_session` safely)
=> feat: add voiceflow:interact event to differentiate from voiceflow:save_session (DX-1078)

packages/react-chat/e2e/extensions.html, packages/react-chat/e2e/extensions.spec.ts, packages/react-chat/e2e/utils.ts, packages/react-chat/src/components/SystemResponse/ExtensionMessage.tsx, packages/react-chat/src/components/SystemResponse/SystemMessage.tsx, packages/react-chat/src/components/SystemResponse/constants.ts, packages/react-chat/src/components/SystemResponse/types.ts, packages/react-chat/src/contexts/RuntimeContext/traces/EffectExtensions.trace.ts, packages/react-chat/src/contexts/RuntimeContext/traces/NoReply.trace.ts, packages/react-chat/src/contexts/RuntimeContext/traces/ResponseExtensions.trace.ts, packages/react-chat/src/contexts/RuntimeContext/useRuntimeState.ts, packages/react-chat/src/dtos/AssistantOptions.dto.ts, packages/react-chat/src/dtos/Extension.dto.ts, packages/react-chat/src/utils/assistant.test.ts, packages/react-chat/src/utils/assistant.ts, packages/react-chat/src/utils/chat.ts, packages/react-chat/typings/global.d.ts
**Fixes or implements DX-1100**
Add extensions (`effect` and `response`) support to the WebChat
=> feat: effect and response extension support (DX-1100)

examples/live-agent/src/use-live-agent.hook.ts, packages/react-chat/package.json, packages/react-chat/src/contexts/RuntimeContext/useRuntimeState.ts, packages/react-chat/src/dtos/ChatConfig.dto.ts, packages/react-chat/src/types/session.ts, packages/react-chat/src/utils/broadcast.ts, yarn.lock
**Fixes or implements PL-000**
The `react-chat` sends a launch/general request which sets `payload: null`. This is problematic because the documented types of `base-types` and `@voiceflow/dtos` does not permit setting this payload to `null`. These requests will also fail Zod validation. 
Updated `@voiceflow/dtos` to the latest version, which contains the latest definitions of the request types. Replace some uses of `BaseRequest.BaseRequest` from `@voiceflow/base-types` with the `BaseRequest` type from `@voiceflow/dtos`. Finally, fixed some of the malformed request types.
N/A
N/A
1. https://github.com/voiceflow/react-chat/pull/141
2. https://github.com/voiceflow/general-runtime/pull/816
- Renaming of interfaces (API routes, request/response interface, …
=> fix: malformed request payloads (PL-1037)

README.md, package.json, packages/react-chat/package.json
I think as part of @effervescentia the local workflow get replaced by storybook.
I've personally found it very helpful because vite allows for HMR while doing dev work. Also the READMEs were out of date.
https://github.com/voiceflow/react-chat/pull/139
=> fix: add local development workflow (ENG-158)

apps/documentation/src/components/StoryEmbed.tsx, packages/chat/src/components/Button/Button.story.tsx, packages/chat/src/components/Button/index.tsx, packages/chat/src/components/FeedbackButton/FeedbackButton.interface.ts, packages/chat/src/components/FeedbackButton/FeedbackButton.story.tsx, packages/chat/src/components/FeedbackButton/FeedbackButton.test.tsx, packages/chat/src/components/FeedbackButton/index.tsx, packages/chat/src/components/Header/Header.story.tsx, packages/chat/src/components/Header/index.tsx, packages/chat/src/dtos/Palette.dto.ts, packages/chat/src/hooks/usePalette.ts, packages/chat/src/storybook/decorators.tsx, packages/chat/src/types/IThemedComponent.ts, packages/chat/src/types/index.ts
Removed `IThemedComponent` - components shouldn't be aware of the 'theme' of the chat widget.  
They all rely on variables, that should be defined on the outer most wrapper of the Chat Widget.
Added a decorator called `WithPalette` to wrap stories, and this defines all the `inlineVars` with the default palette.  
Created a hook called `usePalette` - similar to `useTheme` but will get the whole palette defined from the `AssistantInfo` object (which is defined by the user)
=> feat: aligning theme colors across components (COR-0000)

packages/chat/src/components/Carousel/hooks.ts, packages/chat/src/components/Carousel/styles.css.ts, packages/chat/src/components/SystemResponse/SystemResponse.story.tsx
=> fix: add white background to carousel (DSN-2538)

packages/chat/src/components/NewChat/index.tsx, packages/chat/src/components/ScrollToBottom/index.tsx, packages/chat/src/contexts/AutoScrollContext.tsx
This should fix: COR-3903 and COR-3884
=> fix: scroll to bottom button (COR-3903)

README.md, packages/react-chat/src/views/ChatWidget/index.tsx
Update from `April 15th` -> `June 15th`
=> feat: update deprecation message to users
