voiceflow/react-chat

- src/views/ChatWidget/styled.ts
small one for https://voiceflow.atlassian.net/browse/CT-1044
> fix: animate styles (CT-1044)

- package.json
- src/hooks/useRuntime.ts
- src/utils/actions.ts
- src/utils/url.ts
- yarn.lock
**Fixes or implements CT-1048**
I basically did a carbon copy of how the prototype tool handles it:
https://github.com/voiceflow/creator-app/blob/729ff17e2d558fc43ce7140497ca0716656df33f/packages/creator-app/src/pages/Prototype/components/PrototypeDialog/utils.ts#L52-L60
> fix: open url for actions (CT-1048)

- src/hooks/useRuntime.ts
- src/views/ChatWidget/index.tsx
I had to switch it to a `useRef` because there's no other way the `send` function, especially when it gets added by `registerStep` will have the up to date value of the `hasEnded` state.
This prevents any interactions with the chat after ending.
> fix: prevent interaction on end (CT-000)

- src/components/SystemResponse/hooks.ts
- src/hooks/useRuntime.ts
- src/views/ChatWidget/index.tsx
for this, I had to add a new state to the runtime, a new indicator element.
Also had to make some modifications to the SystemResponse `showIndicator`
> fix: indicator loading state method (CT-1042)

- iframe/vite.config.ts
- index.html
- package.json
- vite.config.ts
made a separate `iframe` folder that will output the iframe code to `/iframe/dist/bundle.mjs`
added an `index.html` file with the bundle :)
> fix: iframe scaffolding (CT-000)

- packages/react-chat/package.json
- packages/react-chat/src/browser/utils.ts
- packages/react-chat/src/components/Feedback/index.tsx
- packages/react-chat/src/components/SystemResponse/index.tsx
- packages/react-chat/src/hooks/useRuntime.ts
- packages/react-chat/src/views/ChatWindow/index.tsx
- packages/widget/package.json
- yarn.lock
**Fixes or implements CT-2052**
Extracted the specific properties and event name from general-runtime and brought to react-chat.
Also, included the AI message together in the feedback event.
I still have to publ
> feat: finalize logic for feedback (CT-2052)

- packages/react-chat/index.html
> feat: disable widget zoom (CV3-286)

- packages/widget/src/session.ts
> fix: sessions

- packages/react-chat/src/components/Card/index.tsx
- packages/react-chat/src/runtime.ts
If the card is completely empty, don't show it.
> fix: filter empty cards (BUG-601)

- packages/react-chat/.depcheckrc
- packages/react-chat/package.json
- packages/react-chat/src/runtime.ts
- packages/widget/src/api/listeners.ts
- yarn.lock
Validate all response types to pervent corruption.
> fix: validate responses through dtos

- packages/react-chat/src/components/Card/styled.ts
**Fixes or implements CV3-307**
- Fix card overflow issue
> feat: fix card overflow issue (CV3-307)

- .circleci/continue-config.yml
- package.json
**Fixes or implements DX-869**
Update to use node 20 and volta
> build: use node 20 and volta (DX-869)

- .vscode/settings.json
- packages/react-chat/src/components/Text/Markdown.tsx
> fix: markdown render (CT-000)

- packages/react-chat/e2e/embedded.spec.ts
- packages/react-chat/e2e/overlay.spec.ts
- packages/react-chat/examples/index.html
- packages/react-chat/src/dtos/ChatConfig.dto.test.ts
- packages/react-chat/src/dtos/ChatConfig.dto.ts
Fixes the `autostart` option's default value
> fix: autostart default value (DX-1087)

- packages/react-chat/src/components/Card/Card.story.tsx
- packages/react-chat/src/components/Card/styled.ts
- packages/react-chat/src/components/Carousel/Carousel.story.tsx
> fix: card title wrapping(DX-1132)

- packages/react-chat/package.json
- yarn.lock
**Fixes or implements COR-2142**
> fix: bumps dtos package [bugfix] (COR-2142)

- packages/react-chat/src/contexts/RuntimeContext/runtime.utils.test.ts
- packages/react-chat/src/contexts/RuntimeContext/runtime.utils.ts
- packages/react-chat/src/contexts/RuntimeContext/useRuntimeState.ts
**Fixes or implements COR-2196**
Allows a user to enter a buttons text in the input to trigger the button interaction.  
Ignore case and trimmed input string, to make logic similar to the prototype tool here: https://github.com/voiceflow/creator-app/blob/df87090ca7fb33b02eb6e22824923446fc267021/apps/creator-app/src/pages/Prototype/hooks/prototype.ts#L93
> feat: allow button action by entering button label (COR-2196)

- examples/live-agent/README.md
- packages/react-chat/src/utils/broadcast.ts
**Fixes or implements COR-2745**
Update documentation links to new links
> fix: update document links (COR-2745)

- .circleci/continue-config.yml
- packages/react-chat/package.json
adds chromatic to circleCI post-build steps
> chore: chromatic setup(DX-1999)

- packages/react-chat/package.json
- yarn.lock
the following error occured before the update:
> fix: update dtos version(TEC-000)

- packages/react-chat/src/contexts/RuntimeContext/useRuntimeState.ts
- packages/react-chat/src/dtos/ChatConfig.dto.ts
- packages/sdk-runtime/src/runtime/index.ts
- packages/sdk-runtime/src/runtime/runtime.interface.ts
- packages/sdk-runtime/src/runtime/runtime.service.prototype.ts
- packages/sdk-runtime/src/sdk/sdk.service.ts
> feat: prototype runtime (COR-000)

- packages/chat/src/components/Button/Inline.tsx
- packages/chat/src/components/Button/constants.ts
- packages/chat/src/components/Button/index.ts
- packages/chat/src/components/Button/reset.css.ts
- packages/chat/src/components/Button/styles.css.ts
- packages/chat/src/components/SystemResponse/index.tsx
- packages/chat/src/components/SystemResponse/styled.ts
- packages/chat/src/styles/colors.css.ts
- packages/chat/src/styles/colors.ts
- packages/chat/src/styles/sizes.ts
- packages/chat/vitest.config.mts
Added the `InlineButton` component, which replaces the `Secondary` Button that was displayed as 'actions' inside the `SystemMessage` component.
Also did some work here to create the colors dynamically according to the color the user chose as their 'brand'.
The colors are off, because I need to figure out the correct ratio between them, but we can do that at a later time.
> feat: add InlineButton component (COR-2143)

- packages/chat/package.json
> fix: export dist css file

- apps/documentation/src/theme.config.tsx
> fix: force light theme and show selector (COR-0000)

- packages/react-chat/src/components/SystemResponse/SystemResponse.story.tsx
- packages/react-chat/src/components/Text/schema.ts
We want to allow users to use tel, mailTo and other protocols as hyperlinks.
> fix: adds support for tel and other hyperlink protocols (DLC-228)

- apps/documentation/src/pages/atomic/launcher/index.mdx
- packages/chat/src/components/Launcher/Launcher.story.tsx
- packages/chat/src/components/Launcher/styles.css.ts
> feat: touch ups for the launcher button (COR-0000)

- .github/workflows/docs.yml
> fix: testing storybook deployment (COR-0000)

- .github/workflows/docs.yml
> fix: should fix storybook deployment

- .github/workflows/docs.yml
> chore: update github-pages-deploy-action version (COR-0000)

- packages/chat/src/components/NewChat/NewChat.css.ts
- packages/chat/src/components/NewChat/index.tsx
- packages/chat/src/components/NewFooter/index.tsx
> feat: add 'Start new chat' button (COR-0000)

- packages/chat/src/components/Launcher/styles.css.ts
- packages/chat/src/components/SystemResponse/index.tsx
- packages/chat/src/views/ChatWidget/index.tsx
- packages/chat/src/views/ChatWidget/styles.css.ts
> fix: adjust chat position above launcher (COR-0000)

- packages/chat/src/components/Launcher/styles.css.ts
- packages/chat/src/components/MessageInput/MessageInput.story.tsx
- packages/chat/src/components/MessageInput/index.tsx
- packages/chat/src/components/NewChat/NewChat.story.tsx
- packages/chat/src/components/NewChat/index.tsx
- packages/chat/src/components/NewFooter/NewFooter.story.tsx
- packages/chat/src/components/NewFooter/index.tsx
- packages/chat/src/components/ScrollToBottom/index.tsx
- packages/chat/src/components/SystemResponse/index.tsx
- packages/chat/src/views/ChatWidget/index.tsx
- packages/chat/src/views/ChatWidget/styles.css.ts
- packages/chat/src/views/ChatWindow/index.tsx
> fix: some scrolling issues & message sending (COR-0000)

- packages/chat/src/components/Launcher/styles.css.ts
- packages/chat/src/components/MessageInput/MessageInput.story.tsx
- packages/chat/src/components/MessageInput/index.tsx
- packages/chat/src/components/NewChat/NewChat.css.ts
- packages/chat/src/components/NewChat/NewChat.story.tsx
- packages/chat/src/components/NewChat/index.tsx
- packages/chat/src/components/NewFooter/NewFooter.story.tsx
- packages/chat/src/components/NewFooter/index.tsx
- packages/chat/src/components/ScrollToBottom/index.tsx
- packages/chat/src/components/SystemResponse/index.tsx
- packages/chat/src/components/SystemResponse/styles.css.ts
- packages/chat/src/views/ChatWidget/index.tsx
- packages/chat/src/views/ChatWidget/styles.css.ts
- packages/chat/src/views/ChatWindow/index.tsx
> fix: minor inline-buttons adjustment (COR-0000)

- apps/documentation/src/pages/atomic/avatar.mdx
- apps/documentation/src/pages/atomic/buttons.mdx
- apps/documentation/src/pages/atomic/feedback-button.mdx
- apps/documentation/src/pages/atomic/launcher.mdx
- apps/documentation/src/pages/atomic/send-button.mdx
- apps/documentation/src/pages/atomic/user-message.mdx
- apps/documentation/src/pages/atomic/welcome-message.mdx
- apps/documentation/src/pages/molecules/card.mdx
- apps/documentation/src/pages/molecules/header.mdx
- apps/documentation/src/pages/molecules/link-preview.mdx
Removed all the useless folders and renamed `index.mdx` to their respective component names, so they'll all be a single level deep in the navigation tree.
> fix: sorting out the docs pages (COR-0000)

- apps/documentation/src/components/ChatConfigOptions/index.tsx
- apps/documentation/src/components/ChatScript/index.tsx
- apps/documentation/src/pages/_app.tsx
- apps/documentation/src/pages/_document.tsx
- apps/documentation/src/pages/index.mdx
> fix: ProjectID configurable Chat on Docs (DSN-000)

- apps/documentation/src/pages/molecules/carousel.mdx
- packages/chat/src/components/Button/styles.css.ts
- packages/chat/src/components/Card/styles.css.ts
- packages/chat/src/components/Carousel/Carousel.story.tsx
- packages/chat/src/components/Carousel/styles.css.ts
- packages/chat/src/components/Header/index.tsx
- packages/chat/src/components/Header/styles.css.ts
- packages/chat/src/components/NewChat/index.tsx
- packages/chat/src/components/ScrollToBottom/index.tsx
- packages/chat/src/components/ScrollToBottom/styles.css.ts
> feat: ui review for carousel component (COR-0000)

- packages/chat/src/components/NewChat/NewChat.story.tsx
- packages/chat/src/components/SystemResponse/Indicator.css.ts
> fix: add top margin to the loading state (DSN-2511)

- packages/chat/src/styles.css
> fix: font weight of headers should be 600 (DSN-2507)

- packages/chat/src/views/ChatWidget/styles.css.ts
> fix: widget width (DSN-2509)

- examples/live-chat/package.json
- examples/live-chat/src/main.tsx
- yarn.lock
> fix: add regenerator-runtime to the live-chat example (COR-0000)

- apps/documentation/src/pages/atomic/typing-indicator.mdx
- packages/chat/src/components/NewChat/NewChat.story.tsx
- packages/chat/src/components/TypingIndicator/TypingIndicator.story.tsx
- packages/chat/src/stories.ts
- packages/chat/src/storybook/decorators.tsx
> feat: add TypingIndicator to the docs (COR-0000)

- apps/documentation/src/components/ChatScript/embedded.tsx
- apps/documentation/src/pages/chat.tsx
- apps/documentation/src/scripts/import-chat.sh
- packages/chat/src/components/NewChat/index.tsx
- packages/chat/src/components/NewFooter/NewFooter.story.tsx
- packages/chat/src/components/NewFooter/index.tsx
- packages/chat/src/contexts/RuntimeContext/useRuntimeState.ts
- packages/chat/src/views/ChatWidget/index.tsx
- packages/chat/src/views/ChatWidget/styles.css.ts
- packages/chat/src/views/ChatWindow/index.tsx
- packages/chat/src/views/ChatWindow/styles.css.ts
Added an 'embed' option to the apps/documentation live demo.  
Made some adjustments to the chat window so the height will work in both modes.
* Also removed the 'Start new chat' button, when restarting, and now only show prompt.
> feat: adjust chat to work in embedded mode as well (COR-3851)

- packages/chat/src/views/ChatWindow/index.tsx
> fix: conditionally executed hook (DSN-000)

- packages/chat/src/components/MessageInput/AudioInputButton.tsx
- packages/chat/src/components/MessageInput/MessageInput.css.ts
- packages/chat/src/components/MessageInput/index.tsx
> fix: Mic button active state + dynamic border radius (DSN-2518)

- apps/documentation/src/styles/globals.css
- apps/documentation/src/theme.config.tsx
> fix: docs dark mode (DSN-2542)

- packages/chat/src/components/NewFooter/NewFooter.css.ts
> fix: themed link on footer (DSN-2536)

- packages/chat/src/components/MessageInput/MessageInput.css.ts
- packages/chat/src/components/NewChat/index.tsx
> fix: ui glitch (COR-0000)

- packages/chat/src/components/Header/styles.css.ts
- packages/chat/src/components/NewFooter/NewFooter.css.ts
- packages/chat/src/components/SystemResponse/styles.css.ts
- packages/chat/src/components/UserResponse/styles.css.ts
- packages/chat/src/components/WelcomeMessage/WelcomeMessage.css.ts
- packages/chat/src/views/ChatWidget/index.tsx
> feat: Animate in widget components (DSN-2530)

- .circleci/continue-config.yml
Skip "UI Tests" required check for gtmq branches
> build(ci): skip UI Tests for gtmq (DSN-2573)

- packages/chat/src/components/AgentMessage/AgentMessage.css.ts
- packages/chat/src/components/AgentMessage/AgentMessage.story.tsx
- packages/chat/src/components/FeedbackButton/FeedbackButton.interface.ts
- packages/chat/src/components/FeedbackButton/index.tsx
- packages/chat/src/components/SystemResponse/index.tsx
- packages/chat/src/components/SystemResponse/styles.css.ts
- packages/chat/src/components/SystemResponse/types.ts
- packages/chat/src/contexts/RuntimeContext/traces/StreamedMessage.trace.ts
- packages/chat/src/contexts/RuntimeContext/useRuntimeState.ts
> fix: Streamed messages with animation and avatar (DSN-2653)
